name: Deployment
run-name: Deploy builded frontend app
on:
  workflow_run:
    workflows: [Build and Release]
    types: [completed]
jobs:
  Deployment:
    runs-on: ubuntu-latest
    environment: TAILSCALE
    steps:
      - name: Configure SSH
        run: echo "Deploying..."
      - uses: webfactory/ssh-agent@v0.9.0
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Configure Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:server
      - name: Copying file
        run: |
          ls -lah
          touch testfile
          echo "Hello" >> testfile
          scp -o StrictHostKeyChecking=no testfile irul@ubuntu.zebroid-gila.ts.net:~/testfile
      - name: Restore git global config
        if: always()
        run: |
          MATCH=$(grep -o 'git@key-[^"]*\.github\.com:.*/[^"]*' ~/.gitconfig)
          git config --global --remove-section url.${MATCH}
